In [ ]:

from pathlib import Path
import pandas as pd

# Directorio raíz del proyecto
BASE_DIR = Path.cwd()

#Comprobar si el script se está ejecutando desde la carpeta "notebooks"
if BASE_DIR.name == "notebooks":
    BASE_DIR = BASE_DIR.parent

DATA_DIR = BASE_DIR / "data"

print("Carpeta del proyecto:", BASE_DIR)
print("\nArchivos disponibles:")

for archivo in DATA_DIR.glob("*.csv"):
    print("-", archivo.name)

Carpeta del proyecto: c:\Users\nayen\EP2-VD-002V-Caso-StreamView-Analytics

Archivos disponibles:
- netflix_movies_detailed_up_to_2025.csv
- netflix_tv_shows_detailed_up_to_2025.csv

Carga de Datos

In [2]:

# Cargar las dos fuentes existentes
peliculas = pd.read_csv(
    DATA_DIR / "netflix_movies_detailed_up_to_2025.csv"
)

series = pd.read_csv(
    DATA_DIR / "netflix_tv_shows_detailed_up_to_2025.csv"
)

# Revisar dimensiones
print("PELÍCULAS")
print("Filas y columnas:", peliculas.shape)
print("Columnas:", peliculas.columns.tolist())

print("\nSERIES")
print("Filas y columnas:", series.shape)
print("Columnas:", series.columns.tolist())

PELÍCULAS
Filas y columnas: (16000, 18)
Columnas: ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'genres', 'language', 'description', 'popularity', 'vote_count', 'vote_average', 'budget', 'revenue']

SERIES
Filas y columnas: (16000, 16)
Columnas: ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'genres', 'language', 'description', 'popularity', 'vote_count', 'vote_average']

Exploración inicial

In [3]:

# 1. Resumen general de las dos fuentes

for nombre, df in [
    ("Películas", peliculas),
    ("Series", series)
]:
    print(f"\n{'=' * 50}")
    print(nombre.upper())
    print("=" * 50)

    print("Dimensiones:", df.shape)
    print("Registros duplicados:", df.duplicated().sum())
    print("IDs duplicados:", df["show_id"].duplicated().sum())
    print("Valores nulos:", df.isna().sum().sum())

    print("\nNulos por columna:")
    print(df.isna().sum().sort_values(ascending=False))

    print("\nTipos de datos:")
    print(df.dtypes)

==================================================
PELÍCULAS
==================================================
Dimensiones: (16000, 18)
Registros duplicados: 0
IDs duplicados: 0
Valores nulos: 17041

Nulos por columna:
duration        16000
country           466
cast              204
director          132
description       132
genres            107
type                0
show_id             0
title               0
date_added          0
rating              0
release_year        0
language            0
popularity          0
vote_count          0
vote_average        0
budget              0
revenue             0
dtype: int64

Tipos de datos:
show_id           int64
type                str
title               str
director            str
cast                str
country             str
date_added          str
release_year      int64
rating          float64
duration        float64
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
budget            int64
revenue           int64
dtype: object

==================================================
SERIES
==================================================
Dimensiones: (16000, 16)
Registros duplicados: 0
IDs duplicados: 9
Valores nulos: 18099

Nulos por columna:
director        10965
description      3206
country          1797
cast             1157
genres            974
type                0
title               0
show_id             0
release_year        0
date_added          0
duration            0
rating              0
language            0
popularity          0
vote_count          0
vote_average        0
dtype: int64

Tipos de datos:
show_id           int64
type                str
title               str
director            str
cast                str
country             str
date_added          str
release_year      int64
rating          float64
duration            str
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
dtype: object

Revisar ambos archivos y su calidad

In [4]:

# 1. Resumen general de las dos fuentes

for nombre, df in [
    ("Películas", peliculas),
    ("Series", series)
]:
    print(f"\n{'=' * 50}")
    print(nombre.upper())
    print("=" * 50)

    print("Dimensiones:", df.shape)
    print("Registros duplicados:", df.duplicated().sum())
    print("IDs duplicados:", df["show_id"].duplicated().sum())
    print("Valores nulos:", df.isna().sum().sum())

    print("\nNulos por columna:")
    print(df.isna().sum().sort_values(ascending=False))

    print("\nTipos de datos:")
    print(df.dtypes)

==================================================
PELÍCULAS
==================================================
Dimensiones: (16000, 18)
Registros duplicados: 0
IDs duplicados: 0
Valores nulos: 17041

Nulos por columna:
duration        16000
country           466
cast              204
director          132
description       132
genres            107
type                0
show_id             0
title               0
date_added          0
rating              0
release_year        0
language            0
popularity          0
vote_count          0
vote_average        0
budget              0
revenue             0
dtype: int64

Tipos de datos:
show_id           int64
type                str
title               str
director            str
cast                str
country             str
date_added          str
release_year      int64
rating          float64
duration        float64
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
budget            int64
revenue           int64
dtype: object

==================================================
SERIES
==================================================
Dimensiones: (16000, 16)
Registros duplicados: 0
IDs duplicados: 9
Valores nulos: 18099

Nulos por columna:
director        10965
description      3206
country          1797
cast             1157
genres            974
type                0
title               0
show_id             0
release_year        0
date_added          0
duration            0
rating              0
language            0
popularity          0
vote_count          0
vote_average        0
dtype: int64

Tipos de datos:
show_id           int64
type                str
title               str
director            str
cast                str
country             str
date_added          str
release_year      int64
rating          float64
duration            str
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
dtype: object

Revisar la consistencia de los datos

In [8]:

# 2. Revisar consistencia de las fuentes

for nombre, df in [
    ("Películas", peliculas),
    ("Series", series)
]:
    print(f"\n--- {nombre.upper()} ---")

    print("\nTipos de contenido:")
    print(df["type"].value_counts(dropna=False))

    print("\nRango de años:")
    print(df["release_year"].describe())

    print("\nValores financieros:")
    columnas_financieras = [
        c for c in ["budget", "revenue"] if c in df.columns
    ]

    if columnas_financieras:
        print(df[columnas_financieras].describe())

    print("\nEjemplos de registros:")
    display(df.head(3))

--- PELÍCULAS ---

Tipos de contenido:
type
Movie    16000
Name: count, dtype: int64

Rango de años:
count    16000.000000
mean      2017.500000
std          4.609916
min       2010.000000
25%       2013.750000
50%       2017.500000
75%       2021.250000
max       2025.000000
Name: release_year, dtype: float64

Valores financieros:
             budget       revenue
count  1.600000e+04  1.600000e+04
mean   8.766792e+06  2.446308e+07
std    2.912450e+07  1.116977e+08
min    0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00
50%    0.000000e+00  0.000000e+00
75%    2.200000e+06  1.654473e+06
max    4.600000e+08  2.799439e+09

Ejemplos de registros:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868

--- SERIES ---

Tipos de contenido:
type
TV Show    16000
Name: count, dtype: int64

Rango de años:
count    16000.000000
mean      2017.500000
std          4.609916
min       2010.000000
25%       2013.750000
50%       2017.500000
75%       2021.250000
max       2025.000000
Name: release_year, dtype: float64

Valores financieros:

Ejemplos de registros:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
0,33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
1,32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
2,37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600

In [9]:

print("=== PELÍCULAS ===")
print("Total de registros:", len(peliculas))
print("Duración nula:", peliculas["duration"].isna().sum())
print("Duración no nula:", peliculas["duration"].notna().sum())

print("\n=== SERIES ===")
print("Total de registros:", len(series))
print("IDs duplicados:", series["show_id"].duplicated().sum())

duplicados = series[
    series.duplicated("show_id", keep=False)
].sort_values("show_id")

display(
    duplicados[["show_id", "title", "release_year", "duration"]]
)

print("\n=== DATOS FINANCIEROS ===")
for columna in ["budget", "revenue"]:
    print(f"{columna}:")
    print("  Ceros:", (peliculas[columna] == 0).sum())
    print("  Nulos:", peliculas[columna].isna().sum())
    print("  Negativos:", (peliculas[columna] < 0).sum())

=== PELÍCULAS ===
Total de registros: 16000
Duración nula: 16000
Duración no nula: 0

=== SERIES ===
Total de registros: 16000
IDs duplicados: 9

,show_id,title,release_year,duration
15540,252630,Joe Lycett’s United States of Birmingham,2025,1 Seasons
15539,252630,Joe Lycett’s United States of Birmingham,2025,1 Seasons
15358,278867,Ensemble,2025,1 Seasons
15360,278867,Ensemble,2025,1 Seasons
15398,279457,Ghassan & Mina,2025,1 Seasons
15400,279457,Ghassan & Mina,2025,1 Seasons
15479,279739,Settle Down,2025,1 Seasons
15480,279739,Settle Down,2025,1 Seasons
15519,280651,Master in 3 Months: Edo Period,2025,1 Seasons
15520,280651,Master in 3 Months: Edo Period,2025,1 Seasons
15359,281750,الباء تحته نقطة,2025,1 Seasons
15361,281750,الباء تحته نقطة,2025,1 Seasons
15399,283602,رحمة,2025,1 Seasons
15401,283602,رحمة,2025,1 Seasons
15320,283929,Kimi wa Mendou na Konyakusha,2025,1 Seasons
15319,283929,Kimi wa Mendou na Konyakusha,2025,1 Seasons
15439,284416,Par de ideotas,2025,1 Seasons
15440,284416,Par de ideotas,2025,1 Seasons

=== DATOS FINANCIEROS ===
budget:
  Ceros: 11153
  Nulos: 0
  Negativos: 0
revenue:
  Ceros: 10355
  Nulos: 0
  Negativos: 0

Verificar los duplicados y el origen de duration

In [10]:

# A. Comprobar cuántos IDs están repetidos y cuántas filas involucran

conteo_ids = series["show_id"].value_counts()
ids_repetidos = conteo_ids[conteo_ids > 1]

print("Cantidad de IDs repetidos:", len(ids_repetidos))
print("Filas involucradas:", int(ids_repetidos.sum()))
print("\nFrecuencia de cada ID repetido:")
display(ids_repetidos.rename("cantidad_filas").to_frame())

# B. Comprobar si las filas son duplicados exactos
filas_duplicadas = series.duplicated(keep=False)

print("\nFilas que son duplicados exactos en todas las columnas:",
      int(series.duplicated().sum()))

print("\nFilas con show_id repetido:")
display(
    series[series["show_id"].isin(ids_repetidos.index)]
    .sort_values(["show_id", "title"])
)

# C. Investigar la columna duration de películas
print("\n=== DURACIÓN DE PELÍCULAS ===")
print("Tipo de dato:", peliculas["duration"].dtype)
print("Cantidad de valores distintos:",
      peliculas["duration"].nunique(dropna=True))
print("Primeros valores no nulos:")
print(peliculas["duration"].dropna().head(10).tolist())

# D. Comparar el estado de duration en ambas fuentes
print("\n=== DURACIÓN EN SERIES ===")
print("Tipo de dato:", series["duration"].dtype)
print("Valores nulos:", series["duration"].isna().sum())
print("Ejemplos de valores:")
print(series["duration"].dropna().head(10).tolist())

Cantidad de IDs repetidos: 9
Filas involucradas: 18

Frecuencia de cada ID repetido:

         cantidad_filas
show_id
283929                2
278867                2
281750                2
279457                2
283602                2
284416                2
279739                2
280651                2
252630                2

Filas que son duplicados exactos en todas las columnas: 0

Filas con show_id repetido:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
15539,252630,TV Show,Joe Lycett’s United States of Birmingham,Nicola Silk,Joe Lycett,United Kingdom,2025-03-01,2025,0.0,1 Seasons,"Documentary, Comedy",en,"It’s no secret that Joe Lycett adores Brum, bu...",11.550,0,0.0
15540,252630,TV Show,Joe Lycett’s United States of Birmingham,Nicola Silk,Joe Lycett,United Kingdom,2025-03-01,2025,0.0,1 Seasons,"Documentary, Comedy",en,"It’s no secret that Joe Lycett adores Brum, bu...",11.531,0,0.0
15358,278867,TV Show,Ensemble,Hayato Kawai,"Haruna Kawaguchi, Hokuto Matsumura, Neru Nagah...",Japan,2025-01-18,2025,7.0,1 Seasons,"Drama, Mystery",ja,"Lawyer Sena Koyama, a realist disillusioned by...",11.044,1,7.0
15360,278867,TV Show,Ensemble,Hayato Kawai,"Haruna Kawaguchi, Hokuto Matsumura, Neru Nagah...",Japan,2025-01-18,2025,7.0,1 Seasons,"Drama, Mystery",ja,"Lawyer Sena Koyama, a realist disillusioned by...",18.407,1,7.0
15398,279457,TV Show,Ghassan & Mina,NaN,"Razzaq Ahmed, Sulaf Jalil",NaN,2025-03-01,2025,0.0,1 Seasons,Comedy,ar,NaN,9.631,0,0.0
15400,279457,TV Show,Ghassan & Mina,NaN,"Razzaq Ahmed, Sulaf Jalil",NaN,2025-03-01,2025,0.0,1 Seasons,Comedy,ar,NaN,16.051,0,0.0
15479,279739,TV Show,Settle Down,NaN,"Alexander Nunez, Tymika Tafari, Nadine Bhabha,...",Canada,2025-02-14,2025,0.0,1 Seasons,NaN,en,Mason is an expert on queer relationships and ...,15.215,0,0.0
15480,279739,TV Show,Settle Down,NaN,"Alexander Nunez, Tymika Tafari, Nadine Bhabha,...",Canada,2025-02-14,2025,0.0,1 Seasons,NaN,en,Mason is an expert on queer relationships and ...,13.135,0,0.0
15519,280651,TV Show,Master in 3 Months: Edo Period,NaN,"Hiroyuki Nojima, Noriko Hidaka",Japan,2025-01-08,2025,0.0,1 Seasons,Talk,ja,An easy-to-understand explanation of the Edo P...,16.794,0,0.0
15520,280651,TV Show,Master in 3 Months: Edo Period,NaN,"Hiroyuki Nojima, Noriko Hidaka",Japan,2025-01-08,2025,0.0,1 Seasons,Talk,ja,An easy-to-understand explanation of the Edo P...,11.996,0,0.0
15359,281750,TV Show,الباء تحته نقطة,NaN,"Mohammad Kheir al-Jarrah, Sawsan Badr, جابر نغ...",United Arab Emirates,2025-03-01,2025,0.0,1 Seasons,"Drama, Comedy",ar,NaN,13.448,0,0.0
15361,281750,TV Show,الباء تحته نقطة,NaN,"Mohammad Kheir al-Jarrah, Sawsan Badr, جابر نغ...",United Arab Emirates,2025-03-01,2025,0.0,1 Seasons,"Drama, Comedy",ar,NaN,18.393,0,0.0
15399,283602,TV Show,رحمة,Mohamed Ali El Mejboud,"Mouna Fettou, Abdellah Didane, Karima Gouit, F...",Morocco,2025-03-02,2025,0.0,1 Seasons,Drama,ar,"After years of believing, I find mercy in a to...",22.466,0,0.0
15401,283602,TV Show,رحمة,Mohamed Ali El Mejboud,"Mouna Fettou, Abdellah Didane, Karima Gouit, F...",Morocco,2025-03-02,2025,0.0,1 Seasons,Drama,ar,"After years of believing, I find mercy in a to...",16.047,0,0.0
15319,283929,TV Show,Kimi wa Mendou na Konyakusha,NaN,NaN,NaN,2025-03-03,2025,0.0,1 Seasons,NaN,ja,NaN,24.577,0,0.0
15320,283929,TV Show,Kimi wa Mendou na Konyakusha,NaN,NaN,NaN,2025-03-03,2025,0.0,1 Seasons,NaN,ja,NaN,21.172,0,0.0
15439,284416,TV Show,Par de ideotas,"Javier G. Williams, Pablo Calasso","Vadhir Derbez, José Eduardo Derbez","United States of America, Mexico",2025-03-07,2025,0.0,1 Seasons,"Reality, Comedy, Documentary",es,Vadhir and José Eduardo Derbez open a pop-up b...,14.680,0,0.0
15440,284416,TV Show,Par de ideotas,"Javier G. Williams, Pablo Calasso","Vadhir Derbez, José Eduardo Derbez","United States of America, Mexico",2025-03-07,2025,0.0,1 Seasons,"Reality, Comedy, Documentary",es,Vadhir and José Eduardo Derbez open a pop-up b...,14.553,0,0.0

=== DURACIÓN DE PELÍCULAS ===
Tipo de dato: float64
Cantidad de valores distintos: 0
Primeros valores no nulos:
[]

=== DURACIÓN EN SERIES ===
Tipo de dato: str
Valores nulos: 0
Ejemplos de valores:
['1 Seasons', '1 Seasons', '1 Seasons', '1 Seasons', '1 Seasons', '1 Seasons', '1 Seasons', '1 Seasons', '1 Seasons', '1 Seasons']

Diferencias dentro de cada grupo de identificadores repetidos

In [11]:

# Auditoría detallada de los IDs repetidos en series

ids_repetidos = (
    series.loc[
        series["show_id"].duplicated(keep=False), "show_id"
    ]
    .unique()
)

for show_id in ids_repetidos:
    grupo = series[series["show_id"] == show_id]

    print(f"\n{'=' * 60}")
    print(f"ID: {show_id} | Filas: {len(grupo)}")

    columnas_diferentes = [
        columna
        for columna in series.columns
        if grupo[columna].nunique(dropna=False) > 1
    ]

    if columnas_diferentes:
        print("Columnas diferentes:", columnas_diferentes)
        display(grupo[["show_id"] + columnas_diferentes])
    else:
        print("Todas las columnas coinciden.")

============================================================
ID: 283929 | Filas: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15319   283929      24.577
15320   283929      21.172

============================================================
ID: 278867 | Filas: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15358   278867      11.044
15360   278867      18.407

============================================================
ID: 281750 | Filas: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15359   281750      13.448
15361   281750      18.393

============================================================
ID: 279457 | Filas: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15398   279457       9.631
15400   279457      16.051

============================================================
ID: 283602 | Filas: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15399   283602      22.466
15401   283602      16.047

============================================================
ID: 284416 | Filas: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15439   284416      14.680
15440   284416      14.553

============================================================
ID: 279739 | Filas: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15479   279739      15.215
15480   279739      13.135

============================================================
ID: 280651 | Filas: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15519   280651      16.794
15520   280651      11.996

============================================================
ID: 252630 | Filas: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15539   252630      11.550
15540   252630      11.531

Investigar por qué las películas no tienen duración

In [12]:

# Auditoría de duración y campos relacionados en películas

columnas_revision = [
    "title", "release_year", "rating",
    "duration", "genres", "popularity",
    "vote_count", "vote_average", "budget", "revenue"
]

print("Valores nulos por columna:")
display(
    peliculas[columnas_revision]
    .isna()
    .sum()
    .sort_values(ascending=False)
    .to_frame("nulos")
)

print("\nEjemplos de películas:")
display(peliculas[columnas_revision].head(10))

print("\nRegistros con presupuesto o ingresos positivos:")
display(
    peliculas.loc[
        (peliculas["budget"] > 0) | (peliculas["revenue"] > 0),
        ["title", "duration", "budget", "revenue"]
    ].head(10)
)

Valores nulos por columna:

              nulos
duration      16000
genres          107
release_year      0
title             0
rating            0
popularity        0
vote_count        0
vote_average      0
budget            0
revenue           0

Ejemplos de películas:

,title,release_year,rating,duration,genres,popularity,vote_count,vote_average,budget,revenue
0,Shrek Forever After,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",203.893,7449,6.380,165000000,752600867
1,Inception,2010,8.369,NaN,"Action, Science Fiction, Adventure",156.242,37119,8.369,160000000,839030630
2,Harry Potter and the Deathly Hallows: Part 1,2010,7.744,NaN,"Adventure, Fantasy",121.191,19327,7.744,250000000,954305868
3,Tangled,2010,7.600,NaN,"Animation, Family, Adventure",111.762,11638,7.600,260000000,592461732
4,How to Train Your Dragon,2010,7.800,NaN,"Fantasy, Adventure, Animation, Family",110.044,13259,7.800,165000000,494879471
5,Shutter Island,2010,8.200,NaN,"Drama, Thriller, Mystery",101.551,24282,8.200,80000000,294804195
6,The Karate Kid,2010,6.500,NaN,"Action, Adventure, Drama, Family",96.385,6082,6.500,40000000,359126022
7,Iron Man 2,2010,6.800,NaN,"Adventure, Action, Science Fiction",95.255,21222,6.800,200000000,623933331
8,Grown Ups,2010,6.394,NaN,Comedy,93.281,6212,6.394,80000000,271430189
9,Room in Rome,2010,6.416,NaN,"Drama, Romance",90.230,748,6.416,0,844281

Registros con presupuesto o ingresos positivos:

,title,duration,budget,revenue
0,Shrek Forever After,NaN,165000000,752600867
1,Inception,NaN,160000000,839030630
2,Harry Potter and the Deathly Hallows: Part 1,NaN,250000000,954305868
3,Tangled,NaN,260000000,592461732
4,How to Train Your Dragon,NaN,165000000,494879471
5,Shutter Island,NaN,80000000,294804195
6,The Karate Kid,NaN,40000000,359126022
7,Iron Man 2,NaN,200000000,623933331
8,Grown Ups,NaN,80000000,271430189
9,Room in Rome,NaN,0,844281