In [ ]:

from pathlib import Path
import pandas as pd

# Directorio raíz del proyecto
BASE_DIR = Path.cwd()

#Comprobar si el script se está ejecutando desde la carpeta "notebooks"
if BASE_DIR.name == "notebooks":
    BASE_DIR = BASE_DIR.parent

DATA_DIR = BASE_DIR / "data"

print("Carpeta del proyecto:", BASE_DIR)
print("\nArchivos disponibles:")

for archivo in DATA_DIR.glob("*.csv"):
    print("-", archivo.name)

Carpeta del proyecto: c:\Users\nayen\EP2-VD-002V-Caso-StreamView-Analytics

Archivos disponibles:
- netflix_movies_detailed_up_to_2025.csv
- netflix_tv_shows_detailed_up_to_2025.csv

Carga de Datos

In [2]:

# Cargar las dos fuentes existentes
peliculas = pd.read_csv(
    DATA_DIR / "netflix_movies_detailed_up_to_2025.csv"
)

series = pd.read_csv(
    DATA_DIR / "netflix_tv_shows_detailed_up_to_2025.csv"
)

# Revisar dimensiones
print("PELÍCULAS")
print("Filas y columnas:", peliculas.shape)
print("Columnas:", peliculas.columns.tolist())

print("\nSERIES")
print("Filas y columnas:", series.shape)
print("Columnas:", series.columns.tolist())

PELÍCULAS
Filas y columnas: (16000, 18)
Columnas: ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'genres', 'language', 'description', 'popularity', 'vote_count', 'vote_average', 'budget', 'revenue']

SERIES
Filas y columnas: (16000, 16)
Columnas: ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'genres', 'language', 'description', 'popularity', 'vote_count', 'vote_average']

Exploración inicial

In [3]:

# 1. Resumen general de las dos fuentes

for nombre, df in [
    ("Películas", peliculas),
    ("Series", series)
]:
    print(f"\n{'=' * 50}")
    print(nombre.upper())
    print("=" * 50)

    print("Dimensiones:", df.shape)
    print("Registros duplicados:", df.duplicated().sum())
    print("IDs duplicados:", df["show_id"].duplicated().sum())
    print("Valores nulos:", df.isna().sum().sum())

    print("\nNulos por columna:")
    print(df.isna().sum().sort_values(ascending=False))

    print("\nTipos de datos:")
    print(df.dtypes)

==================================================
PELÍCULAS
==================================================
Dimensiones: (16000, 18)
Registros duplicados: 0
IDs duplicados: 0
Valores nulos: 17041

Nulos por columna:
duration        16000
country           466
cast              204
director          132
description       132
genres            107
type                0
show_id             0
title               0
date_added          0
rating              0
release_year        0
language            0
popularity          0
vote_count          0
vote_average        0
budget              0
revenue             0
dtype: int64

Tipos de datos:
show_id           int64
type                str
title               str
director            str
cast                str
country             str
date_added          str
release_year      int64
rating          float64
duration        float64
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
budget            int64
revenue           int64
dtype: object

==================================================
SERIES
==================================================
Dimensiones: (16000, 16)
Registros duplicados: 0
IDs duplicados: 9
Valores nulos: 18099

Nulos por columna:
director        10965
description      3206
country          1797
cast             1157
genres            974
type                0
title               0
show_id             0
release_year        0
date_added          0
duration            0
rating              0
language            0
popularity          0
vote_count          0
vote_average        0
dtype: int64

Tipos de datos:
show_id           int64
type                str
title               str
director            str
cast                str
country             str
date_added          str
release_year      int64
rating          float64
duration            str
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
dtype: object

Revisar ambos archivos y su calidad

In [4]:

# 1. Resumen general de las dos fuentes

for nombre, df in [
    ("Películas", peliculas),
    ("Series", series)
]:
    print(f"\n{'=' * 50}")
    print(nombre.upper())
    print("=" * 50)

    print("Dimensiones:", df.shape)
    print("Registros duplicados:", df.duplicated().sum())
    print("IDs duplicados:", df["show_id"].duplicated().sum())
    print("Valores nulos:", df.isna().sum().sum())

    print("\nNulos por columna:")
    print(df.isna().sum().sort_values(ascending=False))

    print("\nTipos de datos:")
    print(df.dtypes)

==================================================
PELÍCULAS
==================================================
Dimensiones: (16000, 18)
Registros duplicados: 0
IDs duplicados: 0
Valores nulos: 17041

Nulos por columna:
duration        16000
country           466
cast              204
director          132
description       132
genres            107
type                0
show_id             0
title               0
date_added          0
rating              0
release_year        0
language            0
popularity          0
vote_count          0
vote_average        0
budget              0
revenue             0
dtype: int64

Tipos de datos:
show_id           int64
type                str
title               str
director            str
cast                str
country             str
date_added          str
release_year      int64
rating          float64
duration        float64
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
budget            int64
revenue           int64
dtype: object

==================================================
SERIES
==================================================
Dimensiones: (16000, 16)
Registros duplicados: 0
IDs duplicados: 9
Valores nulos: 18099

Nulos por columna:
director        10965
description      3206
country          1797
cast             1157
genres            974
type                0
title               0
show_id             0
release_year        0
date_added          0
duration            0
rating              0
language            0
popularity          0
vote_count          0
vote_average        0
dtype: int64

Tipos de datos:
show_id           int64
type                str
title               str
director            str
cast                str
country             str
date_added          str
release_year      int64
rating          float64
duration            str
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
dtype: object

Revisar la consistencia de los datos

In [8]:

# 2. Revisar consistencia de las fuentes

for nombre, df in [
    ("Películas", peliculas),
    ("Series", series)
]:
    print(f"\n--- {nombre.upper()} ---")

    print("\nTipos de contenido:")
    print(df["type"].value_counts(dropna=False))

    print("\nRango de años:")
    print(df["release_year"].describe())

    print("\nValores financieros:")
    columnas_financieras = [
        c for c in ["budget", "revenue"] if c in df.columns
    ]

    if columnas_financieras:
        print(df[columnas_financieras].describe())

    print("\nEjemplos de registros:")
    display(df.head(3))

--- PELÍCULAS ---

Tipos de contenido:
type
Movie    16000
Name: count, dtype: int64

Rango de años:
count    16000.000000
mean      2017.500000
std          4.609916
min       2010.000000
25%       2013.750000
50%       2017.500000
75%       2021.250000
max       2025.000000
Name: release_year, dtype: float64

Valores financieros:
             budget       revenue
count  1.600000e+04  1.600000e+04
mean   8.766792e+06  2.446308e+07
std    2.912450e+07  1.116977e+08
min    0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00
50%    0.000000e+00  0.000000e+00
75%    2.200000e+06  1.654473e+06
max    4.600000e+08  2.799439e+09

Ejemplos de registros:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868

--- SERIES ---

Tipos de contenido:
type
TV Show    16000
Name: count, dtype: int64

Rango de años:
count    16000.000000
mean      2017.500000
std          4.609916
min       2010.000000
25%       2013.750000
50%       2017.500000
75%       2021.250000
max       2025.000000
Name: release_year, dtype: float64

Valores financieros:

Ejemplos de registros:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
0,33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
1,32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
2,37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600

In [9]:

print("=== PELÍCULAS ===")
print("Total de registros:", len(peliculas))
print("Duración nula:", peliculas["duration"].isna().sum())
print("Duración no nula:", peliculas["duration"].notna().sum())

print("\n=== SERIES ===")
print("Total de registros:", len(series))
print("IDs duplicados:", series["show_id"].duplicated().sum())

duplicados = series[
    series.duplicated("show_id", keep=False)
].sort_values("show_id")

display(
    duplicados[["show_id", "title", "release_year", "duration"]]
)

print("\n=== DATOS FINANCIEROS ===")
for columna in ["budget", "revenue"]:
    print(f"{columna}:")
    print("  Ceros:", (peliculas[columna] == 0).sum())
    print("  Nulos:", peliculas[columna].isna().sum())
    print("  Negativos:", (peliculas[columna] < 0).sum())

=== PELÍCULAS ===
Total de registros: 16000
Duración nula: 16000
Duración no nula: 0

=== SERIES ===
Total de registros: 16000
IDs duplicados: 9

,show_id,title,release_year,duration
15540,252630,Joe Lycett’s United States of Birmingham,2025,1 Seasons
15539,252630,Joe Lycett’s United States of Birmingham,2025,1 Seasons
15358,278867,Ensemble,2025,1 Seasons
15360,278867,Ensemble,2025,1 Seasons
15398,279457,Ghassan & Mina,2025,1 Seasons
15400,279457,Ghassan & Mina,2025,1 Seasons
15479,279739,Settle Down,2025,1 Seasons
15480,279739,Settle Down,2025,1 Seasons
15519,280651,Master in 3 Months: Edo Period,2025,1 Seasons
15520,280651,Master in 3 Months: Edo Period,2025,1 Seasons
15359,281750,الباء تحته نقطة,2025,1 Seasons
15361,281750,الباء تحته نقطة,2025,1 Seasons
15399,283602,رحمة,2025,1 Seasons
15401,283602,رحمة,2025,1 Seasons
15320,283929,Kimi wa Mendou na Konyakusha,2025,1 Seasons
15319,283929,Kimi wa Mendou na Konyakusha,2025,1 Seasons
15439,284416,Par de ideotas,2025,1 Seasons
15440,284416,Par de ideotas,2025,1 Seasons

=== DATOS FINANCIEROS ===
budget:
  Ceros: 11153
  Nulos: 0
  Negativos: 0
revenue:
  Ceros: 10355
  Nulos: 0
  Negativos: 0